version: "3.3"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=prueba
      - POSTGRES_USER=grupoBack
      - POSTGRES_PASSWORD=123admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
